-- Chạy đoạn SQL này trong phần "SQL Editor" trên Supabase để hỗ trợ tính năng Lyrics và Comments

-- 1. Thêm cột lyrics vào bảng songs (nếu chưa có)
ALTER TABLE songs ADD COLUMN IF NOT EXISTS lyrics TEXT;

-- 2. Tạo bảng comments cho bài hát
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    song_id BIGINT REFERENCES songs(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tạo bảng cài đặt người dùng (lưu theme) - tuỳ chọn, mình lưu theme vào localStorage cũng được, nhưng tốt nhất cứ lưu localStorage cho nhanh.
